/*
GENERATED - DO NOT MODIFY - use localio instead.

Created by localio
*/

import Foundation

public extension Strings {
    enum general {}
}

public extension Strings.general {
    static var common_app_name_text: String { "common_app_name_text".localized }
    static var common_app_name_pre_text: String { "common_app_name_pre_text".localized }
    static var common_language_code: String { "common_language_code".localized }
    static var common_cancel_text: String { "common_cancel_text".localized }
    static var common_close_text: String { "common_close_text".localized }
    static var common_accept_text: String { "common_accept_text".localized }
    static var common_done_text: String { "common_done_text".localized }
    static var common_back_text: String { "common_back_text".localized }
    static var common_continue_text: String { "common_continue_text".localized }
    static var common_save_text: String { "common_save_text".localized }
    static var common_edit_text: String { "common_edit_text".localized }
    static var common_yes_text: String { "common_yes_text".localized }
    static var common_no_text: String { "common_no_text".localized }
    static var common_error_text: String { "common_error_text".localized }
    static var common_default_server_error_text: String { "common_default_server_error_text".localized }
    static var common_forgot_password_success_title_text: String { "common_forgot_password_success_title_text".localized }
    static var common_forgot_password_success_message_text: String { "common_forgot_password_success_message_text".localized }
    static var common_loading_text: String { "common_loading_text".localized }
    static var common_mandatory_text: String { "common_mandatory_text".localized }
    static var common_show_password_a11y: String { "common_show_password_a11y".localized }
    static var common_hide_password_a11y: String { "common_hide_password_a11y".localized }
    static var common_force_to_update_text: String { "common_force_to_update_text".localized }
    static var common_optional_update_text: String { "common_optional_update_text".localized }
    static var common_update_app_text: String { "common_update_app_text".localized }
    static var common_update_button: String { "common_update_button".localized }
    static var common_open_app_settings_text: String { "common_open_app_settings_text".localized }
    static var common_mandatory_placeholder_text: String { "common_mandatory_placeholder_text".localized }
    static var common_menu_job_offers_label_text: String { "common_menu_job_offers_label_text".localized }
    static var common_menu_company_label_text: String { "common_menu_company_label_text".localized }
    static var common_menu_candidacies_label_text: String { "common_menu_candidacies_label_text".localized }
    static var common_unauthorized_error_text: String { "common_unauthorized_error_text".localized }
    static var login_title_text: String { "login_title_text".localized }
    static var login_email_text: String { "login_email_text".localized }
    static var login_password_text: String { "login_password_text".localized }
    static var login_send_button: String { "login_send_button".localized }
    static var login_welcome_title_text: String { "login_welcome_title_text".localized }
    static var login_welcome_body_text: String { "login_welcome_body_text".localized }
    static var login_forgot_password_button: String { "login_forgot_password_button".localized }
    static var login_sign_up_text: String { "login_sign_up_text".localized }
    static var login_sign_up_button: String { "login_sign_up_button".localized }
    static var login_error_credentials_text: String { "login_error_credentials_text".localized }
    static var login_forgot_password_title_text: String { "login_forgot_password_title_text".localized }
    static var login_password_subtitle_text: String { "login_password_subtitle_text".localized }
    static var login_password_send_text: String { "login_password_send_text".localized }
    static var login_password_nav_title_text: String { "login_password_nav_title_text".localized }
    static var login_try_later_text: String { "login_try_later_text".localized }
    static var logout_confirmation_title_text: String { "logout_confirmation_title_text".localized }
    static var logout_confirmation_message_text: String { "logout_confirmation_message_text".localized }
    static var logout_confirm_button: String { "logout_confirm_button".localized }
    static var logout_cancel_button: String { "logout_cancel_button".localized }
    static var register_title_text: String { "register_title_text".localized }
    static var register_email_label_text: String { "register_email_label_text".localized }
    static var register_password_label_text: String { "register_password_label_text".localized }
    static var register_confirm_password_label_text: String { "register_confirm_password_label_text".localized }
    static var register_name_label_text: String { "register_name_label_text".localized }
    static var register_lastname_label_text: String { "register_lastname_label_text".localized }
    static var register_role_label_text: String { "register_role_label_text".localized }
    static var register_role_student_text: String { "register_role_student_text".localized }
    static var register_role_tutor_text: String { "register_role_tutor_text".localized }
    static var register_security_code_label_text: String { "register_security_code_label_text".localized }
    static var register_dni_label_text: String { "register_dni_label_text".localized }
    static var register_social_security_label_text: String { "register_social_security_label_text".localized }
    static var register_upload_pdf_button_button: String { "register_upload_pdf_button_button".localized }
    static var register_contact_name_label_text: String { "register_contact_name_label_text".localized }
    static var register_contact_phone_label_text: String { "register_contact_phone_label_text".localized }
    static var register_send_button_button: String { "register_send_button_button".localized }
    static var register_invalid_email_text: String { "register_invalid_email_text".localized }
    static var register_invalid_password_text: String { "register_invalid_password_text".localized }
    static var register_passwords_not_match_text: String { "register_passwords_not_match_text".localized }
    static var register_invalid_dni_text: String { "register_invalid_dni_text".localized }
    static var register_invalid_social_security_text: String { "register_invalid_social_security_text".localized }
    static var register_security_code_required_text: String { "register_security_code_required_text".localized }
    static var register_name_required_text: String { "register_name_required_text".localized }
    static var register_lastname_required_text: String { "register_lastname_required_text".localized }
    static var register_contact_email_label_text: String { "register_contact_email_label_text".localized }
    static var register_role_required_text: String { "register_role_required_text".localized }
    static var register_statement_text: String { "register_statement_text".localized }
    static var register_sub_statement_text: String { "register_sub_statement_text".localized }
    static var register_error_email_exists_text: String { "register_error_email_exists_text".localized }
    static var register_max_length_name_surname_text: String { "register_max_length_name_surname_text".localized }
    static var register_invalid_phone_text: String { "register_invalid_phone_text".localized }
    static var register_register_success_1_text: String { "register_register_success_1_text".localized }
    static var register_register_success_2_text: String { "register_register_success_2_text".localized }
    static var register_validation_error_text: String { "register_validation_error_text".localized }
    static var register_fields_completed_text: String { "register_fields_completed_text".localized }
    static var register_register_try_again_text: String { "register_register_try_again_text".localized }
    static var register_error_firebase_user_null_text: String { "register_error_firebase_user_null_text".localized }
    static var register_error_firebase_token_text: String { "register_error_firebase_token_text".localized }
    static var register_error_by_role_null_text: String { "register_error_by_role_null_text".localized }
    static var register_error_dni_already_exists_text: String { "register_error_dni_already_exists_text".localized }
    static var register_error_role_null_text: String { "register_error_role_null_text".localized }
    static var home_title_text: String { "home_title_text".localized }
    static var home_attach_photo_button: String { "home_attach_photo_button".localized }
    static var home_attach_photo_dialog_button: String { "home_attach_photo_dialog_button".localized }
    static var home_camera_rationale: String { "home_camera_rationale".localized }
    static var home_camera_rejected_permission: String { "home_camera_rejected_permission".localized }
    static var home_logout_button: String { "home_logout_button".localized }
    static var about_title_text: String { "about_title_text".localized }
    static var about_button: String { "about_button".localized }
    static var about_multiple_permissions_rationale: String { "about_multiple_permissions_rationale".localized }
    static var about_multiple_permissions_rejected: String { "about_multiple_permissions_rejected".localized }
    static var candidacy_loading_text: String { "candidacy_loading_text".localized }
    static var candidacy_not_candidacy_text: String { "candidacy_not_candidacy_text".localized }
    static var candidacy_not_candidacy_info_text: String { "candidacy_not_candidacy_info_text".localized }
    static var candidacy_postulation_text: String { "candidacy_postulation_text".localized }
    static var candidacy_status_text: String { "candidacy_status_text".localized }
    static var candidacy_title_text: String { "candidacy_title_text".localized }
    static var candidacy_my_tittle_text: String { "candidacy_my_tittle_text".localized }
    static var candidacy_status_pending_text: String { "candidacy_status_pending_text".localized }
    static var candidacy_status_accepted_text: String { "candidacy_status_accepted_text".localized }
    static var candidacy_status_rejected_text: String { "candidacy_status_rejected_text".localized }
    static var candidacy_list_previous_button: String { "candidacy_list_previous_button".localized }
    static var candidacy_presentation_card_text: String { "candidacy_presentation_card_text".localized }
    static var candidacy_register_text: String { "candidacy_register_text".localized }
    static var candidacy_success_text: String { "candidacy_success_text".localized }
    static var candidacy_singup_success_text: String { "candidacy_singup_success_text".localized }
    static var candidacy_register_error_text: String { "candidacy_register_error_text".localized }
    static var candidacy_type_presentation_card_text: String { "candidacy_type_presentation_card_text".localized }
    static var candidacy_list_next_button: String { "candidacy_list_next_button".localized }
    static var candidacy_title_detail_text: String { "candidacy_title_detail_text".localized }
    static var candidacy_additional_note_hint_text: String { "candidacy_additional_note_hint_text".localized }
    static var candidacy_additional_note_text: String { "candidacy_additional_note_text".localized }
    static var candidacy_accept_button: String { "candidacy_accept_button".localized }
    static var candidacy_reject_button: String { "candidacy_reject_button".localized }
    static var candidacy_dialog_accept_title_text: String { "candidacy_dialog_accept_title_text".localized }
    static var candidacy_dialog_reject_title_text: String { "candidacy_dialog_reject_title_text".localized }
    static var candidacy_dialog_accept_confirm_button: String { "candidacy_dialog_accept_confirm_button".localized }
    static var candidacy_dialog_reject_confirm_button: String { "candidacy_dialog_reject_confirm_button".localized }
    static var candidacy_dialog_confirm_button: String { "candidacy_dialog_confirm_button".localized }
    static var candidacy_dialog_cancel_button: String { "candidacy_dialog_cancel_button".localized }
    static var candidacy_company_comment_text: String { "candidacy_company_comment_text".localized }
    static var candidacy_update_candidacy_text: String { "candidacy_update_candidacy_text".localized }
    static var candidacy_reject_candidacy_alert_text: String { "candidacy_reject_candidacy_alert_text".localized }
    static var candidacy_acept_candidacy_alert_text: String { "candidacy_acept_candidacy_alert_text".localized }
    static var candidacy_confirm_register_text: String { "candidacy_confirm_register_text".localized }
    static var candidacy_question_text: String { "candidacy_question_text".localized }
    static var candidacy_question_to_text: String { "candidacy_question_to_text".localized }
    static var candidacy_register_question_text: String { "candidacy_register_question_text".localized }
    static var candidacy_inscriptions_text: String { "candidacy_inscriptions_text".localized }
    static var company_welcome_message_text: String { "company_welcome_message_text".localized }
    static var company_url_not_valid_text: String { "company_url_not_valid_text".localized }
    static var company_cif_valid_format_text: String { "company_cif_valid_format_text".localized }
    static var company_register_success_1_text: String { "company_register_success_1_text".localized }
    static var company_register_success_2_text: String { "company_register_success_2_text".localized }
    static var company_register_failure_title_text: String { "company_register_failure_title_text".localized }
    static var company_register_failure_message_text: String { "company_register_failure_message_text".localized }
    static var company_incomplete_fields_text: String { "company_incomplete_fields_text".localized }
    static var company_mandatory_fields_text: String { "company_mandatory_fields_text".localized }
    static var company_name_label_text: String { "company_name_label_text".localized }
    static var company_cif_label_text: String { "company_cif_label_text".localized }
    static var company_company_tab_text: String { "company_company_tab_text".localized }
    static var company_sector_label_text: String { "company_sector_label_text".localized }
    static var company_web_label_text: String { "company_web_label_text".localized }
    static var company_create_button: String { "company_create_button".localized }
    static var company_view_company_title_text: String { "company_view_company_title_text".localized }
    static var company_view_company_subtitle_text: String { "company_view_company_subtitle_text".localized }
    static var company_logout_text_text: String { "company_logout_text_text".localized }
    static var company_my_company_label_text_text: String { "company_my_company_label_text_text".localized }
    static var company_loading_company_text: String { "company_loading_company_text".localized }
    static var company_companyreg1_text: String { "company_companyreg1_text".localized }
    static var company_companyreg2_text: String { "company_companyreg2_text".localized }
    static var company_areyousure_text: String { "company_areyousure_text".localized }
    static var company_logo_content_description_text: String { "company_logo_content_description_text".localized }
    static var company_view_company_load_error_text: String { "company_view_company_load_error_text".localized }
    static var company_register_error_name_or_cif_exists_text: String { "company_register_error_name_or_cif_exists_text".localized }
    static var company_update_logo_text: String { "company_update_logo_text".localized }
    static var company_update_logo_success_text: String { "company_update_logo_success_text".localized }
    static var company_upload_logo_text: String { "company_upload_logo_text".localized }
    static var company_logo_upload_error_text: String { "company_logo_upload_error_text".localized }
    static var offer_enter_title_text: String { "offer_enter_title_text".localized }
    static var offer_description_offer_text: String { "offer_description_offer_text".localized }
    static var offer_example_vacancy_text: String { "offer_example_vacancy_text".localized }
    static var offer_enter_address_text: String { "offer_enter_address_text".localized }
    static var offer_example_cp_text: String { "offer_example_cp_text".localized }
    static var offer_complete_name_text: String { "offer_complete_name_text".localized }
    static var offer_example_email_text: String { "offer_example_email_text".localized }
    static var offer_offer_detaill_text: String { "offer_offer_detaill_text".localized }
    static var offer_title_text: String { "offer_title_text".localized }
    static var offer_description_text: String { "offer_description_text".localized }
    static var offer_vacances_text: String { "offer_vacances_text".localized }
    static var offer_start_date_text: String { "offer_start_date_text".localized }
    static var offer_end_date_text: String { "offer_end_date_text".localized }
    static var offer_offer_type_text: String { "offer_offer_type_text".localized }
    static var offer_select_text: String { "offer_select_text".localized }
    static var offer_formation_text: String { "offer_formation_text".localized }
    static var offer_contact_detaill_text: String { "offer_contact_detaill_text".localized }
    static var offer_addrees_text: String { "offer_addrees_text".localized }
    static var offer_postal_code_text: String { "offer_postal_code_text".localized }
    static var offer_contact_name_text: String { "offer_contact_name_text".localized }
    static var offer_contact_email_text: String { "offer_contact_email_text".localized }
    static var offer_phone_text: String { "offer_phone_text".localized }
    static var offer_optional_text: String { "offer_optional_text".localized }
    static var offer_mandatory_title_text: String { "offer_mandatory_title_text".localized }
    static var offer_mandatory_description_text: String { "offer_mandatory_description_text".localized }
    static var offer_mandatory_vacancy_text: String { "offer_mandatory_vacancy_text".localized }
    static var offer_mandatory_cp_text: String { "offer_mandatory_cp_text".localized }
    static var offer_mandatory_name_text: String { "offer_mandatory_name_text".localized }
    static var offer_mandatory_address_text: String { "offer_mandatory_address_text".localized }
    static var offer_phone_format_text: String { "offer_phone_format_text".localized }
    static var offer_mandatory_fields_text: String { "offer_mandatory_fields_text".localized }
    static var offer_fields_selected_text: String { "offer_fields_selected_text".localized }
    static var offer_required_type_text: String { "offer_required_type_text".localized }
    static var offer_select_type_offer_text: String { "offer_select_type_offer_text".localized }
    static var offer_required_degree_text: String { "offer_required_degree_text".localized }
    static var offer_select_degree_text: String { "offer_select_degree_text".localized }
    static var offer_required_dates_text: String { "offer_required_dates_text".localized }
    static var offer_offer_tab_text: String { "offer_offer_tab_text".localized }
    static var offer_max_length_vacances_text: String { "offer_max_length_vacances_text".localized }
    static var offer_select_dates_text: String { "offer_select_dates_text".localized }
    static var offer_invalid_postal_code_text: String { "offer_invalid_postal_code_text".localized }
    static var offer_invalid_date_text: String { "offer_invalid_date_text".localized }
    static var offer_error_dates_text: String { "offer_error_dates_text".localized }
    static var offer_my_candidacy_text: String { "offer_my_candidacy_text".localized }
    static var offer_success_text: String { "offer_success_text".localized }
    static var offer_succefully_offer_text: String { "offer_succefully_offer_text".localized }
    static var offer_detail_screen_title_text: String { "offer_detail_screen_title_text".localized }
    static var offer_create_offer_text: String { "offer_create_offer_text".localized }
    static var offer_type_regular_text: String { "offer_type_regular_text".localized }
    static var offer_type_adults_text: String { "offer_type_adults_text".localized }
    static var offer_type_unknown_text: String { "offer_type_unknown_text".localized }
    static var offer_detail_load_error_text: String { "offer_detail_load_error_text".localized }
    static var error_no_internet_text: String { "error_no_internet_text".localized }
    static var error_session_expired_text: String { "error_session_expired_text".localized }
    static var error_if_exist_name_text: String { "error_if_exist_name_text".localized }
    static var error_if_invalid_date_text: String { "error_if_invalid_date_text".localized }
    static var error_if_exist_cif_text: String { "error_if_exist_cif_text".localized }
    static var error_unknow_error_text: String { "error_unknow_error_text".localized }
    static var offer_list_open_text: String { "offer_list_open_text".localized }
    static var offer_list_close_text: String { "offer_list_close_text".localized }
    static var offer_list_no_offers_text: String { "offer_list_no_offers_text".localized }
    static var offer_list_my_offers_text: String { "offer_list_my_offers_text".localized }
    static var offer_list_active_text: String { "offer_list_active_text".localized }
    static var offer_list_offer_list_nav_text: String { "offer_list_offer_list_nav_text".localized }
    static var offer_list_date_offer_text: String { "offer_list_date_offer_text".localized }
    static var offer_list_closed_text: String { "offer_list_closed_text".localized }
    static var offer_list_formation_text: String { "offer_list_formation_text".localized }
    static var offer_list_vacancies_text: String { "offer_list_vacancies_text".localized }
    static var offer_list_modality_text: String { "offer_list_modality_text".localized }
    static var offer_list_watchers_text: String { "offer_list_watchers_text".localized }
    static var offer_list_inscribe_text: String { "offer_list_inscribe_text".localized }
    static var offer_list_company_text: String { "offer_list_company_text".localized }
    static var offer_list_address_text: String { "offer_list_address_text".localized }
    static var offer_list_postal_code_text: String { "offer_list_postal_code_text".localized }
    static var offer_list_contact_text: String { "offer_list_contact_text".localized }
    static var offer_list_mail_text: String { "offer_list_mail_text".localized }
    static var offer_list_phone_text: String { "offer_list_phone_text".localized }
    static var offer_list_not_offer_text: String { "offer_list_not_offer_text".localized }
    static var offer_list_register_text: String { "offer_list_register_text".localized }
    static var offer_list_icon_description_text: String { "offer_list_icon_description_text".localized }
    static var offer_list_icon_inscribe_text: String { "offer_list_icon_inscribe_text".localized }
    static var offer_list_next_text: String { "offer_list_next_text".localized }
    static var offer_list_previous_text: String { "offer_list_previous_text".localized }
    static var components_sample_title_text: String { "components_sample_title_text".localized }
    static var components_sample_menu_buttons_button: String { "components_sample_menu_buttons_button".localized }
    static var components_sample_menu_textfields_button: String { "components_sample_menu_textfields_button".localized }
    static var components_sample_menu_dialogs_button: String { "components_sample_menu_dialogs_button".localized }
    static var components_sample_menu_pickers_button: String { "components_sample_menu_pickers_button".localized }
    static var components_sample_menu_sign_up_example_button: String { "components_sample_menu_sign_up_example_button".localized }
    static var components_sample_buttons_primary_text: String { "components_sample_buttons_primary_text".localized }
    static var components_sample_buttons_secondary_text: String { "components_sample_buttons_secondary_text".localized }
    static var components_sample_buttons_tertiary_text: String { "components_sample_buttons_tertiary_text".localized }
    static var components_sample_buttons_outlined_text: String { "components_sample_buttons_outlined_text".localized }
    static var components_sample_buttons_enabled_button: String { "components_sample_buttons_enabled_button".localized }
    static var components_sample_buttons_disabled_button: String { "components_sample_buttons_disabled_button".localized }
    static var components_sample_buttons_icon_button: String { "components_sample_buttons_icon_button".localized }
    static var components_sample_textfields_default_label: String { "components_sample_textfields_default_label".localized }
    static var components_sample_textfields_error_label: String { "components_sample_textfields_error_label".localized }
    static var components_sample_textfields_number_label: String { "components_sample_textfields_number_label".localized }
    static var components_sample_textfields_number_placeholder: String { "components_sample_textfields_number_placeholder".localized }
    static var components_sample_textfields_disabled_label: String { "components_sample_textfields_disabled_label".localized }
    static var components_sample_textfields_trailing_icon_label: String { "components_sample_textfields_trailing_icon_label".localized }
    static var components_sample_textfields_password_label: String { "components_sample_textfields_password_label".localized }
    static var components_sample_textfields_suggestions_label: String { "components_sample_textfields_suggestions_label".localized }
    static var components_sample_dialogs_info_dialog_title_text: String { "components_sample_dialogs_info_dialog_title_text".localized }
    static var components_sample_dialogs_info_dialog_message_text: String { "components_sample_dialogs_info_dialog_message_text".localized }
    static var components_sample_dialogs_error_dialog_title_text: String { "components_sample_dialogs_error_dialog_title_text".localized }
    static var components_sample_dialogs_error_dialog_message_text: String { "components_sample_dialogs_error_dialog_message_text".localized }
    static var components_sample_dialogs_warning_dialog_title_text: String { "components_sample_dialogs_warning_dialog_title_text".localized }
    static var components_sample_dialogs_warning_dialog_message_text: String { "components_sample_dialogs_warning_dialog_message_text".localized }
    static var components_sample_dialogs_input_text_dialog_title_text: String { "components_sample_dialogs_input_text_dialog_title_text".localized }
    static var components_sample_dialogs_input_text_dialog_message_text: String { "components_sample_dialogs_input_text_dialog_message_text".localized }
    static var components_sample_dialogs_input_text_dialog_placeholder: String { "components_sample_dialogs_input_text_dialog_placeholder".localized }
    static var components_sample_dialogs_input_text_dialog_snackbar: String { "components_sample_dialogs_input_text_dialog_snackbar".localized }
    static var components_sample_picker_title_text: String { "components_sample_picker_title_text".localized }
    static var components_sample_picker_header_text: String { "components_sample_picker_header_text".localized }
    static var components_sample_picker_birth_date_text: String { "components_sample_picker_birth_date_text".localized }
    static var components_sample_picker_day_text: String { "components_sample_picker_day_text".localized }
    static var components_sample_picker_time_text: String { "components_sample_picker_time_text".localized }
    static var components_sample_picker_hidden_with_check_text: String { "components_sample_picker_hidden_with_check_text".localized }
    static var components_sample_picker_gender_text: String { "components_sample_picker_gender_text".localized }
    static var components_sample_picker_gender_options_header_text: String { "components_sample_picker_gender_options_header_text".localized }
    static var components_sample_picker_list_with_search_text: String { "components_sample_picker_list_with_search_text".localized }
    static var components_sample_picker_placeholder_text: String { "components_sample_picker_placeholder_text".localized }
    static var components_sample_picker_list_text: String { "components_sample_picker_list_text".localized }
    static var components_sample_picker_multiple_choice_text: String { "components_sample_picker_multiple_choice_text".localized }
    static var components_sample_picker_single_choice_text: String { "components_sample_picker_single_choice_text".localized }
    static var components_sample_picker_inline_text: String { "components_sample_picker_inline_text".localized }
    static var components_sample_picker_segmented_text: String { "components_sample_picker_segmented_text".localized }
    static var components_sample_picker_wheel_text: String { "components_sample_picker_wheel_text".localized }
}

private extension String {
    var localized: String {
        NSLocalizedString(self, tableName: "general", bundle: Bundle.module, value: "", comment: "")
    }
}
