source "https://rubygems.org"

gem "fastlane"
gem 'localio', git: 'https://bitbucket.org/mobivery-public/localio', tag: '2.0.4'
gem 'rake'
gem 'danger'
gem 'danger-swiftlint'
gem 'danger-xcode_summary'
gem 'danger-xcov'


plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)